[tool.poetry]
name = "general"
version = "0.1.0"
description = ""
authors = ["boarcoder <boarcoder@proton.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
binarytree = "^6.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
